### ISSUE TITLE
Faile to pre-compile on Julia 0.5.2 Ubuntu 16.04

### ISSUE THREAD

**Issue by loicspace** [JuliaTopOpt/VTKDataTypes.jl#1]
Hi,

This is Loic, I decided to try to visualize my spacecraft model with VTKDataIO now that I was able to export from FUsion 360 a PLY file (From our discussion on Discourse: [visualize-3d-mesh-with-texture](https://discourse.julialang.org/t/visualize-3d-mesh-with-texture/4671/2) but VTKDataTypes fails to pre-compile for me:

```
julia> using VTKDataIO
INFO: Precompiling module VTKDataTypes.
ERROR: LoadError: LoadError: syntax: invalid type signature
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /home/loic/.julia/v0.5/VTKDataTypes/src/types.jl, in expression starting on line 1
while loading /home/loic/.julia/v0.5/VTKDataTypes/src/VTKDataTypes.jl, in expression starting on line 11
ERROR: LoadError: Failed to precompile VTKDataTypes to /home/loic/.julia/lib/v0.5/VTKDataTypes.ji.
```

Am I missing something?
Thanks!

**Comment by mohdibntarek** [comment]
Well it only supports v0.6! If you don't have a huge code base, better move to v0.6 now, it's only a few differences you will have to keep in mind which are summarized in this link. https://github.com/JuliaLang/julia/blob/release-0.6/NEWS.md

Also to use VTKDataIO.jl, you will need a few more setup steps:
1. Get VTK on your computer. I tested it using VTK 7.1.1.
2. Get Python 2.7, and add it to your PATH variable (2nd part is optional but recommended)
3. Get Numpy
4. Add the equivalent path to "C:\Program Files\VTK 7.1.1\bin\Lib\site-packages\vtk" to your PYTHONPATH User environment variable on your computer if you are using Windows, or the equivalent in any other OS. Basically make sure when you open a Python shell, and write `import vtk` that it works.
5. Get PyCall.jl
6. Find your computer's python.exe file, e.g. "C:\Python27\python.exe" and run the following 2 commands in Julia replacing the path below with your own and "\\" with "\\\\":
```
ENV["PYTHON"] = "C:\\Python27\\python.exe"
Pkg.build("PyCall")
```
7. Test the following Julia code and make sure it works.
```
using PyCall
@pyimport vtk as vtk
@pyimport numpy as np
```

And now you are ready to use VTKDataIO, I think! Try this and let me know if you face trouble.

I just realized the title says you are using Ubuntu in which case, the steps will be slightly different. I believe PyCall automatically uses the machine's default Python so you won't need 6, and 2 and 4 will also be the equivalent in Linux.

**Comment by loicspace** [comment]
Hi,

Ah, that explains that. Sadly, I do have a large code base on 0.5 for an application we are developping and I will transition at some point, soon hopefully. At the moment -- or last time I checked -- some of the packages I use are not working just yet on 0.6.
I'll tinker with it on 0.6 independently though because I think some cool things could happen there :)
Thanks for the steps, I may have to try it out with an older version of vtk as it seems it is not trivial on Debian.

Thanks,
Loic
